
# 日志配置
[log]
fileName = "log/runtime.log"
maxSize = 10
maxAge = 3
maxBackups = 3
level = 1


[server]
addr=":8080"


[mysql]
username="root"
password="ysm@121388"
host="127.0.0.1"
port="3306"
dbName="follow"
runMode="debug"

[script_file]
addr="scripts"
runFilename="run"

